"""Add company_website and youtube_url to ContactDetail

Revision ID: 73ee0146e056
Revises: 
Create Date: 2025-09-01 00:21:43.797891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ee0146e056'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_website', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('linkedin',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('instagram',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('facebook',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('twitter',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_detail', schema=None) as batch_op:
        batch_op.alter_column('twitter',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('facebook',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('instagram',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('linkedin',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('company_website')

    # ### end Alembic commands ###
