"""add journal_id to editor_board

Revision ID: 80ca6ade2367
Revises: a112a8843ea0
Create Date: 2025-09-17 00:23:32.607580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ca6ade2367'
down_revision = 'a112a8843ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editor_board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'journal_master', ['journal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editor_board', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('journal_id')

    # ### end Alembic commands ###
