"""Add image_filename to ResearchPaper

Revision ID: a112a8843ea0
Revises: 73ee0146e056
Create Date: 2025-09-01 01:56:18.773921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a112a8843ea0'
down_revision = '73ee0146e056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_paper', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
